spring:
  application:
    name: uaa-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.61.136.215:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: ZnA*rJuuV7A

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
